name: PR Verify

on: [pull_request]

permissions:
  contents: read

concurrency:
  group: pr-verify-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Pre-fetch deps (warm pnpm store)
        run: pnpm fetch
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Run ESLint
        run: pnpm lint

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Pre-fetch deps (warm pnpm store)
        run: pnpm fetch
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: TypeScript type check
        run: pnpm tsc

  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Pre-fetch deps (warm pnpm store)
        run: pnpm fetch
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Check formatting
        run: pnpm format:check

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: '1'
      NODE_ENV: test
      NEXT_PUBLIC_SUPABASE_URL: 'https://example.supabase.co'
      NEXT_PUBLIC_SUPABASE_ANON_KEY: 'anon-key'
      NEXT_PUBLIC_SITE_URL: 'http://localhost:3000'
      DRIZZLE_DATABASE_URL: 'postgres://user:pass@127.0.0.1:5432/db'
      SUPABASE_DB_POOL_URL: 'postgres://user:pass@127.0.0.1:5432/db'
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Pre-fetch deps (warm pnpm store)
        run: pnpm fetch
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Build project
        run: pnpm build
